- name: Demo on Simple playbook
  hosts: all
  vars:
    a: 10
  tasks:
  - name: Task1
    ansible.builtin.debug:
      msg: Hello from playbook

  - name: Task2
    ansible.builtin.debug:
      msg: "new message {{a}}"