#- name: Play for variable
  #hosts: all
  #vars:
   # url: example.com
  tasks:
    - name: Print a value
      hosts: all
      vars:
      url: example.com
      ansible.builtin.debug:
        msg: URL - {{url}}