- name: Play for variable
  hosts: all
  vars:
   url: example.com
   a: 15
   b: 15
  tasks:
    - name: Print a value
      ansible.builtin.debug:
        msg: URL - {{url}}
             A+B - {{a}}+{{b}}
- name: Play for command line variables
  hosts: all
  vars:
   URL:
  tasks:
    - name: Print the url
      ansible.builtin.debug:
        msg:  -"{{URL}}"